services:
  - type: web
    name: n8n-service
    plan: free
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest

    # Render provides PORT and RENDER_EXTERNAL_URL at runtime.
    # We export N8N_* from those and start n8n bound to $PORT.
    startCommand: >
      sh -lc '
      export N8N_PORT="$PORT";
      export N8N_PROTOCOL="https";
      export N8N_EDITOR_BASE_URL="$RENDER_EXTERNAL_URL";
      export WEBHOOK_URL="$RENDER_EXTERNAL_URL";
      export N8N_HOST="$(echo "$RENDER_EXTERNAL_URL" | awk -F[/:] "{print \$4}")";
      n8n start
      '

    envVars:
      - key: N8N_ENCRYPTION_KEY           # REQUIRED: generate a long random string and set it in the dashboard later
        value: CHANGE_ME_STRONG_RANDOM
      - key: N8N_SECURE_COOKIE
        value: "true"
      - key: N8N_HIDE_USAGE_PAGE
        value: "true"
      - key: N8N_DIAGNOSTICS_ENABLED
        value: "false"
      - key: N8N_METRICS
        value: "false"
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: GENERIC_TIMEZONE
        value: America/New_York
      - key: TZ
        value: America/New_York
      # Optional: enable queue-based executions/runners if you need them later
      # - key: N8N_RUNNERS_ENABLED
      #   value: "true"

    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 5

    autoDeploy: true
